### ISSUE TITLE
Bring back the `apiKey` feature.

### ISSUE THREAD

**Issue by valeriyo** [bugsnag/bugsnag-android-gradle-plugin#349]
### Describe the bug
The `apiKey` feature was removed (https://github.com/bugsnag/bugsnag-android-gradle-plugin/commit/a3288c34dc0288e0832a8f02d497d11ea7b74b22) without proper justification and that change needs to be reverted.

I asked this question why it was removed (https://github.com/bugsnag/bugsnag-android-gradle-plugin/issues/348) and @xander-jones closed the ticket with "it caused confusion in the past" as the explanation.

The latest runtime library 5.3.0 support specifying the apiKey in code, outside of `AndroidManifest.xml` - so, now there is more confusion because the latest plugin 5.6.0 does not support this, while there is plenty of integration docs for the library, which show examples how to avoid putting it in `AndroidManifest.xml`.

I'm evaluating Bugsnag for my company, and this is a blocker.

**Comment by valeriyo** [comment]
https://docs.bugsnag.com/platforms/android/configuration-options/:

![Uploading image.png…]()

**Comment by mattdyoung** [comment]
Hi @valeriyo 

We're generally moving towards config being defined in the manifest rather than code wherever possible and are unlikely to prioritize reversing the change to where the API key is defined unless there is significant interest in this from customers.

If you wanted to work around the need to define the API key in the manifest you could fork the [bugsnag-android-gradle-plugin](https://github.com/bugsnag/bugsnag-android-gradle-plugin) repository for your own usage or use our [upload APIs](https://docs.bugsnag.com/api/) directly rather than using the Bugsnag plugin.

**Comment by valeriyo** [comment]
Subscription canceled. You know, keep looking for the interest to spike.
