### ISSUE TITLE
[React Native] Improve docs on sourcemap upload / plugin setup

### ISSUE THREAD

**Issue by sterlingwes** [bugsnag/bugsnag-android-gradle-plugin#360]
### Describe the bug
The bundle sourcemap upload task for react native will not register if the plugin is not applied _after_ the main react native plugin is applied (and the RN bundle task is registered).

This plugin fails silently here if configured otherwise: https://github.com/bugsnag/bugsnag-android-gradle-plugin/blob/76731fac917454eba14cd643167b97e6c8b14f48/src/main/kotlin/com/bugsnag/android/gradle/BugsnagPlugin.kt#L447

The bug is unclear documentation & no misconfiguration warnings in the Gradle build output

### Steps to reproduce
Have a `project/app/build.gradle` that looks something like this:

```gradle
apply plugin: "com.android.application"
apply plugin: "com.bugsnag.android.gradle"

// some other stuff....

apply from: "../../node_modules/react-native/react.gradle"

// some more stuff....

bugsnag {
    enabled = true
    uploadReactNativeMappings = true
    overwrite = true
}
```

And run `./gradlew assembleRelease` or otherwise do a non-debug build

### Environment
* Android Studio version: 4.0
* Android Gradle version: 6.2
* Bugsnag manifest section (if modified): N/A

**Comment by mattdyoung** [comment]
Hi @sterlingwes 

Thanks for highlighting this.

The intention is that for most projects you'd be able to use the `@bugsnag/react-native-cli` which automates this and applies the plugins in the correct order:
https://docs.bugsnag.com/platforms/react-native/react-native/

The issue with outputting a misconfiguration warning is that for non-RN Android projects we wouldn't want to output any warning but there's not a reliable way to detect that across all of the types of project we support.

Based on your feedback we've just made an update to our documentation for manual setup to clarify the ordering that's required:
https://docs.bugsnag.com/platforms/react-native/react-native/manual-setup/#android

**Comment by sterlingwes** [comment]
> The issue with outputting a misconfiguration warning is that for non-RN Android projects we wouldn't want to output any warning but there's not a reliable way to detect that across all of the types of project we support.

The line I referenced above is only relevant for React Native

**Comment by mattdyoung** [comment]
Hi @sterlingwes 

> The line I referenced above is only relevant for React Native

Yes, sorry - that's what I meant. The line runs on all Android projects using our gradle plugin (React Native or not), but is only relevant for React Native projects.

It therefore fails silently, as for non-React Native projects that's the correct thing to do. We wouldn't want to warn if we can't find RN tasks since for a general Android project there may not be any.

Since we support a wide range of React Native versions, there's not a clean, future-proof way of detecting we're in a React Native project and then warn if we don't find the tasks.

Hopefully now the documentation clarifies the required ordering this is unlikely to cause further issues.

Thanks again for your feedback!
