### ISSUE TITLE
Incremental build cache issue

### ISSUE THREAD

**Issue by guilherme-pereira-ifood** [bugsnag/bugsnag-android-gradle-plugin#364]
### Describe the bug
I'm investigating the project build and, after executing these tasks in sequence:
1. `./gradlew clean app:assembleBrazilDebug --no-build-cache`
2. `./gradlew app:assembleBrazilDebug --no-build-cache`

It was expected no tasks were executed, but two of them executed and I found some references to `Bugsnag`, but I'm still not sure it's a `Bugsnag` issue.

![image](https://user-images.githubusercontent.com/45950956/106613087-92361280-6548-11eb-8cbe-1a81b86c39a8.png)

I'd like your help to understand if it's related to Bugsnag or if it was a coincidence.

### Steps to reproduce
In a project with bugsnag configured:
1. `./gradlew clean app:assembleBrazilDebug --no-build-cache --scan`
2. `./gradlew app:assembleBrazilDebug --no-build-cache  --scan`
3. Go to the Build scan page > Timeline tab
4. Filter `OUTCOME` with `SUCCESS`

### Environment
* Android Studio version: 4.1.2
* Android Gradle version: 4.1.2
* Bugsnag Gradle Plugin: 5.7.2

**Comment by xander-jones** [comment]
👋. Hey @guilherme-pereira-ifood,

Bugsnag’s gradle plugin writes a random UUID to the manifest on each build - this is the only reliable way for us to uniquely identify APKs which could all have different code. This random UUID changes the input (what Gradle uses for determining whether it can use cached files, or needs to regenerate) each time and therefore Bugsnag’s Gradle tasks run on each build.

So, regardless of caching options, we'd expect this task to run if the Bugsnag Android Gradle Plugin is enabled for this build type.

There are a couple of methods we’d suggest here if you wanted to stop these tasks running in debug, we'd suggest using the first option if this is a path you'd like to follow:
1. Disable Bugsnag uploads on development builds, and enable it on CI builds. By default the Bugsnag plugin is disabled for debug build variants (specifically, any build variant with “debug” in the name). You can change which builds use the Bugsnag Android Gradle Plugin in the module's `build.gradle` file: https://docs.bugsnag.com/build-integrations/gradle/#installation
1. The `com.bugsnag.android.BUILD_UUID` meta-data element can be manually set in the `AndroidManifest.xml`, so you can change this only when you want to, effectively changing the inputs for Gradle only when desired. This does need to be a unique value for every time the code changes however, because otherwise the correct mappings won’t be uploaded. This is more advanced and improves build performance but it comes with the potential for mappings to go wrong.
