### ISSUE TITLE
Gradle 8.0/AGP 8.0 support

### ISSUE THREAD

**Issue by ZacSweers** [bugsnag/bugsnag-android-gradle-plugin#497]
This isn't really a feature request but rather a status request. AGP 8.0 and Gradle 8.0 are around the corner, and currently a warning is printed in bugsnag's plugin warning about usage with them. Are there any known issues? Are there any bugs/blockers to support day-1?

**Comment by lemnik** [comment]
Hi @ZacSweers AGP 8.0 / Gradle 8.0 compatibility are being worked on. From what I've seen so far there shouldn't be any blockers for pure Android (Kotlin, Java, NDK) apps.

**Comment by lemnik** [comment]
Hi @ZacSweers, we have a 8.0.0-beta01 release out now: https://github.com/bugsnag/bugsnag-android-gradle-plugin/releases/tag/v8.0.0-beta01

It has a known issue around early configuration (`Configuration '****' was resolved during configuration time.`) that we'll be working to fix in the next release, but should otherwise work.
